# Generated by Django 3.1.3 on 2020-12-01 07:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_auto_20201130_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='home',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='photos'),
        ),
    ]
